import { expect, test, type Locator, type Page } from '@playwright/test';
async function choose(page: Page, trigger: Locator, label: string) { await trigger.click(); await page.getByRole('option', { name: label, exact: true }).click(); }
async function state(page: Page) { return page.evaluate(() => { const root = JSON.parse(localStorage.getItem('anumat-hackathon-v1')!); return root.spaces[root.active]; }); }
async function create(page: Page, title: string, type = 'Task', parent?: string) {
  await page.getByRole('button', { name: 'New task', exact: true }).first().click();
  const drawer = page.getByRole('dialog', { name: 'New task', exact: true });
  await drawer.getByRole('textbox', { name: 'Task', exact: true }).fill(title);
  if (type !== 'Task') await choose(page, drawer.getByRole('combobox', { name: 'Work item type' }), type);
  if (parent) await choose(page, drawer.getByRole('combobox', { name: 'Parent item' }), parent);
  return drawer;
}
test('workflow gates verify expected results and evidence, and persist task requirements', async ({ page }, info) => {
  await page.goto('/tasks');
  await page.getByRole('button', { name: 'Task options' }).click();
  await page.getByRole('menuitem', { name: 'Manage statuses' }).click();
  const settings = page.getByRole('dialog', { name: 'Task statuses' });
  await settings.getByRole('button', { name: 'Use recommended workflow' }).click();
  await settings.getByRole('textbox', { name: 'Default readiness requirements' }).fill('Scope is agreed');
  await settings.getByRole('textbox', { name: 'Default completion requirements' }).fill('Results reviewed');
  await page.screenshot({ path: `test-results/task-settings-${info.project.name}.png`, animations: 'disabled' });
  await settings.getByRole('button', { name: 'Save statuses' }).click();
  let drawer = await create(page, 'Deliver verified report');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  await page.getByRole('button', { name: 'Deliver verified report', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'In progress');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(drawer.getByText('Describe the expected outcome before moving this task.')).toBeVisible();
  await drawer.getByRole('textbox', { name: 'Expected outcome', exact: true }).fill('Team receives an accurate report');
  const criteria = drawer.getByRole('region', { name: 'Acceptance criteria', exact: true });
  await criteria.getByRole('button', { name: 'Add requirement' }).click();
  await criteria.getByRole('textbox').fill('All totals match source records');
  await drawer.getByRole('checkbox', { name: 'Verify Scope is agreed' }).press('Space');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect.poll(async () => (await state(page)).tasks.find((item: { title: string }) => item.title === 'Deliver verified report').status).toBe('doing');
  await page.getByRole('checkbox', { name: 'Mark “Deliver verified report” done' }).press('Space');
  await expect(page.getByText('Verify every acceptance criterion first.')).toBeVisible();
  await page.getByRole('button', { name: 'Deliver verified report', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await drawer.getByRole('checkbox', { name: 'Verify All totals match source records' }).press('Space');
  await drawer.getByRole('checkbox', { name: 'Verify Results reviewed' }).press('Space');
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'Done');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(drawer.getByText('Record completion evidence before marking this task done.')).toBeVisible();
  await drawer.getByRole('textbox', { name: 'Completion evidence', exact: true }).fill('Reviewed report: /documents/report');
  await page.screenshot({ path: `test-results/task-requirements-${info.project.name}.png`, animations: 'disabled' });
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await page.reload();
  const item = (await state(page)).tasks.find((item: { title: string }) => item.title === 'Deliver verified report');
  expect(item.status).toBe('done'); expect(item.evidence).toContain('Reviewed report'); expect(item.acceptanceCriteria[0].done).toBe(true);
  await page.getByRole('tab', { name: 'Hierarchy', exact: true }).click();
  await page.getByRole('button', { name: 'Deliver verified report', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'Backlog');
  await drawer.getByRole('checkbox', { name: 'Verify Results reviewed' }).press('Space');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  const reopened = (await state(page)).tasks.find((item: { title: string }) => item.title === 'Deliver verified report');
  expect(reopened.status).toBe('todo'); expect(reopened.completion[0].done).toBe(false);

  await page.evaluate(() => { localStorage.setItem('anumat-locale', 'km'); localStorage.setItem('anumat-theme', 'dark'); });
  await page.reload();
  await page.getByRole('tab', { name: 'ឋានានុក្រម', exact: true }).click();
  await page.getByRole('button', { name: 'Deliver verified report', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'លទ្ធផលរំពឹងទុក', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0);
  await page.screenshot({ path: `test-results/task-km-dark-${info.project.name}.png`, animations: 'disabled' });
});
test('hierarchy requires valid parents and blocks completion and deletion of unfinished parents', async ({ page }, info) => {
  await page.goto('/tasks');
  let drawer = await create(page, 'Customer onboarding', 'Epic');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  drawer = await create(page, 'Send welcome pack', 'Story', 'Customer onboarding');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  drawer = await create(page, 'Prepare welcome email', 'Subtask');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  await expect(drawer.getByText('A subtask needs a parent story, task, or bug.')).toBeVisible();
  await choose(page, drawer.getByRole('combobox', { name: 'Parent item' }), 'Send welcome pack');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  await page.getByRole('tab', { name: 'Hierarchy' }).click();
  await expect(page.getByRole('heading', { name: 'Work hierarchy' })).toBeVisible();
  await page.screenshot({ path: `test-results/task-hierarchy-${info.project.name}.png`, animations: 'disabled' });
  await page.getByRole('checkbox', { name: 'Mark “Customer onboarding” done' }).press('Space');
  await expect(page.getByText('Complete child items before marking their parent done.')).toBeVisible();
  await page.getByRole('button', { name: 'Customer onboarding', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await expect(drawer.getByRole('button', { name: 'Delete', exact: true })).toHaveCount(0);
  await choose(page, drawer.getByRole('combobox', { name: 'Work item type' }), 'Task');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(drawer.getByText('Move child items to another parent before changing this type.')).toBeVisible();
  await page.reload();
  const items = (await state(page)).tasks;
  expect(items.find((item: { title: string }) => item.title === 'Prepare welcome email').parentId).toBe(items.find((item: { title: string }) => item.title === 'Send welcome pack').id);
});

test('configured transitions restrict previous statuses and RACI roles', async ({ page }, info) => {
  await page.goto('/tasks');
  await page.getByRole('button', { name: 'Task options' }).click();
  await page.getByRole('menuitem', { name: 'Manage statuses' }).click();
  const settings = page.getByRole('dialog', { name: 'Task statuses' });
  const doing = settings.getByRole('listitem').filter({ has: page.getByRole('textbox', { name: 'Name of status 2', exact: true }) });
  await doing.getByRole('checkbox', { name: 'Allow from any status' }).press('Space');
  await doing.getByRole('checkbox', { name: 'To do', exact: true }).press('Space');
  const review = settings.getByRole('listitem').filter({ has: page.getByRole('textbox', { name: 'Name of status 4', exact: true }) });
  await review.getByRole('checkbox', { name: 'Responsible (R)' }).press('Space');
  await review.getByRole('checkbox', { name: 'Accountable (A)' }).press('Space');
  await settings.getByRole('button', { name: 'Save statuses' }).click();
  let drawer = await create(page, 'Check review permissions');
  await choose(page, drawer.getByRole('combobox', { name: 'Owner', exact: true }), 'Alex Tan');
  await choose(page, drawer.getByRole('combobox', { name: 'Accountable approver', exact: true }), 'Alex Tan');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  await page.getByRole('button', { name: /^Account:/ }).click();
  await page.getByRole('menuitem', { name: /Alex Tan/ }).click();
  await page.getByRole('button', { name: 'Check review permissions', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'In progress');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(drawer.getByText('This transition is not allowed. Follow the configured workflow.')).toBeVisible();
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'In review');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(drawer.getByText('Your responsibility does not allow this status change.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Manage statuses' })).toHaveCount(0);
  await drawer.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('tab', { name: 'Hierarchy' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0);
});

test('responsible person requests sign-off and accountable person completes the task', async ({ page }) => {
  await page.goto('/tasks');
  let drawer = await create(page, 'Approve verified delivery');
  await choose(page, drawer.getByRole('combobox', { name: 'Owner', exact: true }), 'Alex Tan');
  await drawer.getByRole('button', { name: 'Add task', exact: true }).click();
  await page.getByRole('button', { name: /^Account:/ }).click();
  await page.getByRole('menuitem', { name: /Alex Tan/ }).click();
  await page.getByRole('button', { name: 'Approve verified delivery', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await expect(drawer.getByRole('combobox', { name: 'Accountable approver', exact: true })).toBeDisabled();
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'Done');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  let item = (await state(page)).tasks.find((item: { title: string }) => item.title === 'Approve verified delivery');
  expect(item.status).toBe('review'); expect(item.signOffRequestedAt).toBeTruthy();
  await page.getByRole('button', { name: /^Account:/ }).click();
  await page.getByRole('menuitem', { name: /Dara Sok/ }).click();
  await choose(page, page.getByRole('combobox', { name: 'Whose tasks' }), 'Everyone');
  await page.getByRole('button', { name: 'Approve verified delivery', exact: true }).click();
  drawer = page.getByRole('dialog', { name: 'Task', exact: true });
  await choose(page, drawer.getByRole('combobox', { name: 'Status', exact: true }), 'Done');
  await drawer.getByRole('button', { name: 'Save', exact: true }).click();
  item = (await state(page)).tasks.find((item: { title: string }) => item.title === 'Approve verified delivery');
  expect(item.status).toBe('done'); expect(item.signOffRequestedAt).toBeUndefined();
});
