import type { Meta, StoryObj } from '@storybook/react-vite';
import { App } from '../../App';
const meta = {title:'Apps/Workspace',component:App,parameters:{layout:'fullscreen',docs:{description:{component:'Full production routes with the actual shell, in-memory demo data, and working navigation. Reload or switch stories to reset. The HR apps contain local lifecycle prototypes and explicitly illustrative payroll.'}}}} satisfies Meta<typeof App>;
export default meta;
type Story=StoryObj<typeof meta>;
export const Discover:Story={parameters:{route:'/discover'}};
export const ApprovalDashboard:Story={parameters:{route:'/home?app=approvals'}};
export const TaskDashboard:Story={parameters:{route:'/home?app=tasks'}};
export const MeetingDashboard:Story={parameters:{route:'/home?app=meetings'}};
export const SurveyDashboard:Story={parameters:{route:'/home?app=surveys'}};
export const Requests:Story={parameters:{route:'/requests'}};
export const NewRequest:Story={parameters:{route:'/requests/new'}};
export const Approvals:Story={parameters:{route:'/approvals'}};
export const ProcessBuilder:Story={parameters:{route:'/processes/storybook-purchase'}};
export const Processes:Story={parameters:{route:'/processes'}};
export const Tasks:Story={parameters:{route:'/tasks'}};
export const TasksEmpty:Story={parameters:{route:'/tasks',empty:true}};
export const TasksMember:Story={parameters:{route:'/tasks',role:'member'}};
export const TasksViewer:Story={parameters:{route:'/tasks',role:'viewer'}};
export const TaskPeople:Story={parameters:{route:'/tasks/people'}};
export const TaskPeopleViewer:Story={parameters:{route:'/tasks/people',role:'viewer'}};
export const ApprovalPeople:Story={parameters:{route:'/approvals/people'}};
export const MeetingPeople:Story={parameters:{route:'/meetings/people'}};
export const SurveyPeople:Story={parameters:{route:'/surveys/people'}};
export const Surveys:Story={parameters:{route:'/surveys'}};
export const SurveysEmpty:Story={parameters:{route:'/surveys',empty:true}};
export const SurveyBuilder:Story={parameters:{route:'/surveys/new'}};
export const SurveysMember:Story={parameters:{route:'/surveys',role:'member'}};
export const Meetings:Story={parameters:{route:'/meetings'}};
export const NewMeeting:Story={parameters:{route:'/meetings/new'}};
export const MeetingsEmpty:Story={parameters:{route:'/meetings',empty:true}};
export const NotificationPreferences:Story={parameters:{route:'/settings/notifications'}};
export const Documents:Story={parameters:{route:'/documents'}};
export const Insights:Story={parameters:{route:'/insights'}};
export const WorkspacePeople:Story={parameters:{route:'/settings/people'}};
export const TelegramPreview:Story={parameters:{route:'/telegram'}};
export const NotFound:Story={parameters:{route:'/unknown'}};
